# nivel2-db-backend.yml
# NIVEL 2 · Base de datos + backend
# Uso: docker compose -f nivel2-db-backend.yml up -d --build
include:
  - nivel1-db.yml

services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stockya_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "12345"
    depends_on:
      db:
        condition: service_healthy